#PBS -N SOR_JAVA_Improved_PERF_NUMA_DRAM_Counters__USER_ONLY_431
#PBS -l walltime=20:00:00
#PBS -q mei
#PBS -m abe
#PBS -M carlos.sa01@gmail.com

#PBS -lnodes=1:r431:ppn=24

# Machine USED (Interactive usage)
# node=`echo $HOSTNAME | awk -F'.' '{print $1}'`


# Machine USED (job-exclusive usage)
read -r node<$PBS_NODEFILE

perf="/usr/bin/perf"
$perf --version



############ Information about algorithm to run ################
alg="SOR_Improved"
exe="$HOME/NUMA_Aware_Thesis/java_codes/jar/SOR_Improved_sm.jar"
size=5
nthreads=8
################################################################

########################## Tests configuration ###############################
# Java Dir 
JAVA8="/share/apps/java/jdk1.8.0_20/bin/java"

# Tests to perform with perf
DEFAULT="$JAVA8 -jar $exe -5 $size $nthreads"
LOCAL_ACCESS="numactl --cpubind=0 --membind=0 $JAVA8 -jar $exe -5 $size $nthreads"
REMOTE_ACCESS="numactl --cpubind=0 --membind=1 $JAVA8 -jar $exe -5 $size $nthreads"


# Array with all tests
declare -a TEST=("$DEFAULT" "$LOCAL_ACCESS" "$REMOTE_ACCESS")
#############################################################################


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#	COUNTERS INFO
#
# 0xf
# MEM_UNCORE_RETIRED - Load instructions retired (Precise Event)
#	0x02 : PMU : [LOCAL_HITM] : Load instructions retired that HIT modified data in sibling core 
#	0x08 : PMU : [LOCAL_DRAM_AND_REMOTE_CACHE_HIT] : Load instructions retired local dram and remote cache HIT data sources 
#	0x10 : PMU : [REMOTE_DRAM] : Load instructions retired remote DRAM and remote home-remote cache HITM 
#	0x04 : PMU : [REMOTE_HITM] : Retired loads that hit remote socket in modified state 
#	0x20 : PMU : [OTHER_LLC_MISS] : Load instructions retired other LLC miss 
#
#
#
# 0x1b7
# OFFCORE_RESPONSE_0 - Offcore response 0 (must provide at least one request and one response umasks) 
#	 0x100 : PMU : [UNCORE_HIT] : Response: counts L3 Hit: local or remote home requests that hit L3 cache in the uncore with no coherency actions required (snooping)
#	0x200 : PMU : [OTHER_CORE_HIT_SNP] : Response: counts L3 Hit: local or remote home requests that hit L3 cache in the uncore and was serviced by another core with a cross core snoop where no modified copies were found (clean)
#	0x800 : PMU : [REMOTE_CACHE_HITM] :  Response: counts L3 Hit: local or remote home requests that hit a remote L3 cacheline in modified (HITM) state
#	0x1000 : PMU : [LOCAL_DRAM_AND_REMOTE_CACHE_HIT] : Response: counts L3 Miss: local home requests that missed the L3 cache and were serviced by local DRAM or a remote cache
#	0x2000 : PMU : [REMOTE_DRAM] : Response: counts L3 Miss: remote home requests that missed the L3 cache and were serviced by remote DRAM
#
#
#	0x01 : PMU : [DMND_DATA_RD] : Request: counts the number of demand and DCU prefetch data reads of full and partial cachelines as well as demand data page table entry cacheline reads. Does not count L2 data read prefetches or instruction fetches
#	0x02 : PMU : [DMND_RFO] : Request: counts the number of demand and DCU prefetch reads for ownership (RFO) requests generated by a write to data cacheline. Does not count L2 RFO
#	0x04 : PMU : [DMND_IFETCH] : Request: counts the number of demand and DCU prefetch instruction cacheline reads. Does not count L2 code read prefetches
#	0x10 : PMU : [PF_DATA_RD] : Request: counts the number of data cacheline reads generated by L2 prefetchers
#	0x20 : PMU : [PF_RFO] 	  : Request: counts the number of RFO requests generated by L2 prefetchers
#	0x40 : PMU : [PF_IFETCH]  : Request: counts the number of code reads generated by L2 prefetchers
#
#
#		
# 0x1bb
# OFFCORE_RESPONSE_1 - Offcore response 1 (must provide at least one request and one response umasks)
#	0x100 : PMU : [UNCORE_HIT] : Response: counts L3 Hit: local or remote home requests that hit L3 cache in the uncore with no coherency actions required (snooping)
#	0x200 : PMU : [OTHER_CORE_HIT_SNP] : Response: counts L3 Hit: local or remote home requests that hit L3 cache in the uncore and was serviced by another core with a cross core snoop where no modified copies were found (clean)
#	0x800 : PMU : [REMOTE_CACHE_HITM] : Response: counts L3 Hit: local or remote home requests that hit a remote L3 cacheline in modified (HITM) state
#	0x1000 : PMU : [LOCAL_DRAM_AND_REMOTE_CACHE_HIT] : Response: counts L3 Miss: local home requests that missed the L3 cache and were serviced by local DRAM or a remote cache
#	0x2000 : PMU : [REMOTE_DRAM] : Response: counts L3 Miss: remote home requests that missed the L3 cache and were serviced by remote DRAM
#	
#
#	0x01 : PMU : [DMND_DATA_RD] : Request: counts the number of demand and DCU prefetch data reads of full and partial cachelines as well as demand data page table entry cacheline reads. Does not count L2 data read prefetches or instruction fetches
#	0x02 : PMU : [DMND_RFO] : Request: counts the number of demand and DCU prefetch reads for ownership (RFO) requests generated by a write to data cacheline. Does not count L2 RFO
#	0x04 : PMU : [DMND_IFETCH] : Request: counts the number of demand and DCU prefetch instruction cacheline reads. Does not count L2 code read prefetches
#	0x10 : PMU : [PF_DATA_RD]  : Request: counts the number of data cacheline reads generated by L2 prefetchers
#	0x20 : PMU : [PF_RFO] 	   : Request: counts the number of RFO requests generated by L2 prefetchers
#	0x40 : PMU : [PF_IFETCH]   : None : Request: counts the number of code reads generated by L2 prefetchers
#	
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


echo "${TEST[@]}"

for t in "${TEST[@]}"
do

        echo "Test: $t"

	###### MEM_UNCORE_RETIRED (0xf) ###### 
	perf stat -e r53020f:u $t 

	perf stat -e r53080f:u $t 

	perf stat -e r53100f:u $t 

	perf stat -e r53040f:u $t 
	
	perf stat -e r53200f:u $t 


	###### OFFCORE_RESPONSE_0 (0x1b7) ###### 

	perf stat -e r5301b7:u,r1:u $t

	perf stat -e r5301b7:u,r2:u $t 

	perf stat -e r5301b7:u,r4:u $t

	perf stat -e r5301b7:u,r10:u $t

	perf stat -e r5301b7:u,r20:u $t

	perf stat -e r5301b7:u,r40:u $t

	perf stat -e r5301b7:u,r100:u $t

	perf stat -e r5301b7:u,r200:u $t

	perf stat -e r5301b7:u,r800:u $t

	perf stat -e r5301b7:u,r1000:u $t
	
	perf stat -e r5301b7:u,r2000:u $t




	###### OFFCORE_RESPONSE_1 (0x1bb) ###### 
	
	perf stat -e r5301bb:u,r1:u $t

	perf stat -e r5301bb:u,r2:u $t

	perf stat -e r5301bb:u,r4:u $t
	
	perf stat -e r5301bb:u,r10:u $t
	
	perf stat -e r5301bb:u,r20:u $t
	
	perf stat -e r5301bb:u,r40:u $t

	perf stat -e r5301bb:u,r100:u $t

	perf stat -e r5301bb:u,r200:u $t

	perf stat -e r5301bb:u,r800:u $t

	perf stat -e r5301bb:u,r1000:u $t

	perf stat -e r5301bb:u,r2000:u $t
done


echo
echo
echo
echo
echo ".......Done!"
