#PBS -N SOR_JAVA_Improved_PERF_NUMA_DRAM_Counters__USER_ONLY
#PBS -l walltime=20:00:00
#PBS -q mei
#PBS -m abe
#PBS -M carlos.sa01@gmail.com

#PBS -lnodes=1:r641:ppn=32

# Machine USED (Interactive usage)
# node=`echo $HOSTNAME | awk -F'.' '{print $1}'`


# Machine USED (job-exclusive usage)
read -r node<$PBS_NODEFILE

perf="/usr/bin/perf"
$perf --version



############ Information about algorithm to run ################
alg="SOR_Improved"
exe="$HOME/NUMA_Aware_Thesis/java_codes/jar/SOR_Improved_sm.jar"
size=5
nthreads=8
################################################################

########################## Tests configuration ###############################
# Java Dir 
JAVA8="/share/apps/java/jdk1.8.0_20/bin/java"

# Tests to perform with perf
DEFAULT_EXEC="$JAVA8 -jar $exe -5 $size $nthreads"
LOCAL_ACCESS_EXEC="numactl --cpubind=0 --membind=0 $JAVA8 -jar $exe -5 $size $nthreads"
REMOTE_ACCESS_EXEC="numactl --cpubind=0 --membind=1 $JAVA8 -jar $exe -5 $size $nthreads"

# Array with all tests
#declare -a TEST=("$DEFAULT_EXEC" "$LOCAL_ACCESS_EXEC" "$REMOTE_ACCESS_EXEC")
declare -a TEST=("$LOCAL_ACCESS_EXEC")

#############################################################################


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#	COUNTERS INFO
#
#
#
# 0xd3
# MEM_LOAD_UOPS_LLC_MISS_RETIRED - Load uops retired that missed the LLC
#	0x01 : PMU : [LOCAL_DRAM]  : Number of retired load uops that missed L3 but were service by local RAM. Does not count hardware prefetches
#	0x0c : PMU : [REMOTE_DRAM] : Number of retired load uops that missed L3 but were service by remote RAM, snoop not needed, snoop miss, snoop hit data not forwarded
#	0x10 : PMU : [REMOTE_HITM] : Number of retired load uops whose data sources was remote HITM
#	0x20 : PMU : [REMOTE_FWD]  : Load uops that miss in the L3 whose data source was forwarded from a remote cache
#
# 0xd2	
# MEM_LOAD_UOPS_LLC_HIT_RETIRED - L3 hit loads uops retired
#	0x02 : PMU : [XSNP_HIT]  : Load LLC Hit and a cross-core Snoop hits in on-pkg core cache
#	0x04 : PMU : [XSNP_HITM] : Load had HitM Response from a core on same SOCKET (shared LLC)
#	0x01 : PMU : [XSNP_MISS] : Load LLC Hit and a cross-core Snoop missed in on-pkg core cache
#	0x08 : PMU : [XSNP_NONE] : Load hit in last-level (L3) cache with no snoop needed
#
#	
# 
# OFFCORE_RESPONSE_0 - Offcore response event (must provide at least one request type and either any_response or any combination of supplier + snoop)
#	0x400000     : PMU : [LLC_MISS_LOCAL]       : Supplier: counts L3 misses to local DRAM
#	0x7f800000   : PMU : [LLC_MISS_REMOTE_DRAM] : Supplier: counts L3 misses to remote DRAM
#	0x800000000  : PMU : [SNP_FWD] 		    : Snoop: counts number of times a snoop was needed and data was forwarded from a REMOTE SOCKET
#	0x1000000000 : PMU : [HITM] 		    : Snoop: counts number of times a snoop was needed and it hitM-ed in LOCAL OR REMOTE CACHE
#	0x2000000000 : PMU : [NON_DRAM] 	    : Snoop: counts number of times target was a non-DRAM system address. This includes MMIO transactions
#
#	
#	0x01 : PMU :  [DMND_DATA_RD] :   number of demand and DCU prefetch data reads of full and partial cachelines as well as demand data page table entry cacheline reads.
#						Does not count L2 data read prefetches or instruction fetches
#	0x02 : PMU :  [DMND_RFO]     :   number of demand and DCU prefetch reads for ownership (RFO) requests generated by a write to data cacheline. 
#						Does not count L2 RFO prefetches
#	0x04 : PMU :  [DMND_IFETCH]  :   number of demand and DCU prefetch instruction cacheline reads. Does not count L2 code read prefetches
#	0x10 : PMU :  [PF_DATA_RD]   :   number of data cacheline reads generated by L2 prefetchers
#	0x20 : PMU :  [PF_RFO] 	     :   number of RFO requests generated by L2 prefetchers
#	0x40 : PMU :  [PF_IFETCH]    :   number of code reads generated by L2 prefetchers
#	0x80 : PMU :  [PF_LLC_DATA_RD] : number of L3 prefetcher requests to L2 for loads
#	0x100 : PMU : [PF_LLC_RFO]    :  number of RFO requests generated by L2 prefetcher
#	0x200 : PMU : [PF_LLC_IFETCH] :  number of L2 prefetcher requests to L3 for instruction fetches
#
# 
# OFFCORE_RESPONSE_1 - Offcore response event (must provide at least one request type and either any_response or any combination of supplier + snoop)
#	0x400000     : PMU : [LLC_MISS_LOCAL] 	    : Supplier: counts L3 misses to local DRAM
#	0x7f800000   : PMU : [LLC_MISS_REMOTE_DRAM] : Supplier: counts L3 misses to remote DRAM
#	0x800000000  : PMU : [SNP_FWD] 		    : Snoop: counts number of times a snoop was needed and data was forwarded from a remote socket
#	0x1000000000 : PMU : [HITM] 		    : Snoop: counts number of times a snoop was needed and it hitM-ed in local or remote cache
#	0x2000000000 : PMU : [NON_DRAM] 	    : Snoop:  counts number of times target was a non-DRAM system address. This includes MMIO transactions
#	
#
#	0x01 : PMU : [DMND_DATA_RD]   : number of demand and DCU prefetch data reads of full and partial cachelines as well as demand data page table entry cacheline reads. 
#						Does not count L2 data read prefetches or instruction fetches
#	0x02 : PMU : [DMND_RFO]       : number of demand and DCU prefetch reads for ownership (RFO) requests generated by a write to data cacheline. 
#						Does not count L2 RFO prefetches
#	0x04 : PMU : [DMND_IFETCH]    :  number of demand and DCU prefetch instruction cacheline reads. Does not count L2 code read prefetches
#	0x10 : PMU : [PF_DATA_RD]     :  number of data cacheline reads generated by L2 prefetchers
#	0x20 : PMU : [PF_RFO] 	      :  number of RFO requests generated by L2 prefetchers
#	0x40 : PMU : [PF_IFETCH]      :  number of code reads generated by L2 prefetchers
#	0x80 : PMU : [PF_LLC_DATA_RD] :  number of L3 prefetcher requests to L2 for loads
#	0x100 : PMU : [PF_LLC_RFO]    :  number of RFO requests generated by L2 prefetcher
#	0x200 : PMU : [PF_LLC_IFETCH] :  number of L2 prefetcher requests to L3 for instruction fetches
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


for t in "${TEST[@]}"
do
        echo "Test: $t"


	###### MEM_LOAD_UOPS_LLC_MISS_RETIRED (0xd3) ###### 
	echo "Testing MEM_LOAD_UOPS_LLC_MISS_RETIRED (0xd3)"

	echo "0x01 : PMU : [LOCAL_DRAM]"
	perf stat -e r5301d3:u $t 

	echo "0x0c : PMU : [REMOTE_DRAM]"
	perf stat -e r530cd3:u $t 

	echo "0x10 : PMU : [REMOTE_HITM]"
	perf stat -e r5310d3:u $t 

	echo "0x20 : PMU : [REMOTE_FWD]"
	perf stat -e r5320d3:u $t 


	###### MEM_LOAD_UOPS_HIT_MISS_RETIRED (0xd2) ###### 
	echo "MEM_LOAD_UOPS_HIT_MISS_RETIRED (0xd2)" 

	echo "0x02 : PMU : [XSNP_HIT]"
	perf stat -e r5302d2:u $t

	echo "0x04 : PMU : [XSNP_HITM]"
	perf stat -e r5304d2:u $t

	echo "0x01 : PMU : [XSNP_MISS]"
	perf stat -e r5301d2:u $t

	echo "0x08 : PMU : [XSNP_NONE]"
	perf stat -e r5308d2:u $t



	
	###### OFFCORE_RESPONSE_0 (0x1b7) ###### 	
	echo "OFFCORE_RESPONSE_0 (0x1b7)"
	
	# DRAM Memory Counters
	echo "0x400000 : PMU : [LLC_MISS_LOCAL]"
	perf stat -e r5301b7:u,r400000:u $t

	echo "0x7f800000 : PMU : [LLC_MISS_REMOTE_DRAM]"
	perf stat -e r5301b7:u,r7f800000:u $t
	
	echo "0x800000000 : PMU : [SNP_FWD]"
	perf stat -e r5301b7:u,r800000000:u $t

	echo "0x1000000000 : PMU : [HITM]"
	perf stat -e r5301b7:u,r1000000000:u $t

	echo "0x2000000000 : PMU : [NON_DRAM]"
	perf stat -e r5301b7:u,r2000000000:u $t

	# CACHE PREFETCH Counters
	echo "0x01 : PMU : [DMND_DATA_RD]"
	perf stat -e r5301b7:u,r1:u $t 

	echo "0x02 : PMU : [DMND_RFO]"
	perf stat -e r5301b7:u,r2:u $t

	echo "0x04 : PMU : [DMND_IFETCH]"
	perf stat -e r5301b7:u,r4:u $t

	echo "0x10 : PMU : [PF_DATA_RD]"
	perf stat -e r5301b7:u,r10:u $t

	echo "0x20 : PMU : [PF_RFO]"
	perf stat -e r5301b7:u,r20:u $t

	echo "0x40 : PMU : [PF_IFETCH]"
	perf stat -e r5301b7:u,r40:u $t

	echo "0x80 : PMU : [PF_LLC_DATA_RD]"
	perf stat -e r5301b7:u,r80:u $t

	echo "0x100 : PMU : [PF_LLC_RFO]"
	perf stat -e r5301b7:u,r100:u $t

	echo "0x200 : PMU : [PF_LLC_IFETCH]"
	perf stat -e r5301b7:u,r200:u $t




	###### OFFCORE_RESPONSE_1 (0x1bb) ###### 
	echo "OFFCORE_RESPONSE_1 (0x1bb)"
	
	# DRAM Memory Counters
	echo "0x400000 : PMU : [LLC_MISS_LOCAL]"
	perf stat -e r5301bb:u,r400000:u $t

	echo "0x7f800000 : PMU : [LLC_MISS_REMOTE_DRAM]"
	perf stat -e r5301bb:u,r7f800000:u $t

	echo "0x800000000 : PMU : [SNP_FWD]"
	perf stat -e r5301bb:u,r800000000:u $t
	
	echo "0x1000000000 : PMU : [HITM]"
	perf stat -e r5301bb:u,r1000000000:u $t
	
	echo "0x2000000000 : PMU : [NON_DRAM]"
	perf stat -e r5301bb:u,r2000000000:u $t

	# CACHE PREFETCH Counters
	echo "0x01 : PMU : [DMND_DATA_RD]"
	perf stat -e r5301bb:u,r1:u $t
	
	echo "0x02 : PMU : [DMND_RFO]"
	perf stat -e r5301bb:u,r2:u $t
	
	echo "0x04 : PMU : [DMND_IFETCH]"
	perf stat -e r5301bb:u,r4:u $t

	echo "0x10 : PMU : [PF_DATA_RD]"
	perf stat -e r5301bb:u,r10:u $t

	echo "0x20 : PMU : [PF_RFO]"
	perf stat -e r5301bb:u,r20:u $t

	echo "0x40 : PMU : [PF_IFETCH]"
	perf stat -e r5301bb:u,r40:u $t

	echo "0x80 : PMU : [PF_LLC_DATA_RD]"
	perf stat -e r5301bb:u,r80:u $t

	echo "0x100 : PMU : [PF_LLC_RFO]"
	perf stat -e r5301bb:u,r100:u $t

	echo "0x200 : PMU : [PF_LLC_IFETCH]"
	perf stat -e r5301bb:u,r200:u $t
done


echo
echo
echo
echo
echo ".......Done!"
