sudo: false

language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

script:
  - cd benchmarks && make && ./larson/larson 10 7 8 10000 1000 1 4 4
  - if [ $TRAVIS_OS_NAME == linux ]; then cd ../src && make && cd test && make && cd .. && export LD_PRELOAD=$PWD/libhoard.so && ../benchmarks/larson/larson 10 7 8 10000 1000 1 4 4 && ./test/mtest && unset LD_PRELOAD ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then cd ../src && make ; fi

