# generated by configure / remove this line to disable regeneration
prefix="/platform"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/gcc-build/isl/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/gcc-build/isl/../../gcc-5.3.0/isl/include"
package="isl"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "isl"
;; --help) pkg-config --help ; echo Buildscript Of "isl Library"
;; --modversion|--version) echo "0.14"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-lisl /home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/gcc-build/./gmp/libgmp.la"
       :
;; --cflags) echo -I${includedir} "-I/home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/gcc-build/gmp/../../gcc-5.3.0/gmp -I/home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/gcc-build/./gmp"
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
