# All makefile fragments assume that $(srcdir) points to the gcc
# directory, not the language subdir
srcdir = /home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/objdir/../gcc-5.3.0/gcc
-include ./gcc-interface/Makefile
-include ../gcc-interface/Makefile
