BEGIN {
S["am__EXEEXT_FALSE"]=""
S["am__EXEEXT_TRUE"]="#"
S["LTLIBOBJS"]=""
S["LIBOBJS"]=""
S["PICFLAG"]=""
S["TARGET_LIBRARY_FALSE"]=""
S["TARGET_LIBRARY_TRUE"]="#"
S["toolexeclibdir"]="$(libdir)/../lib64"
S["toolexecdir"]="$(libdir)/gcc-lib/$(target_alias)"
S["target_all"]="libzgcj.la"
S["CPP"]="gcc -E"
S["OTOOL64"]=""
S["OTOOL"]=""
S["LIPO"]=""
S["NMEDIT"]=""
S["DSYMUTIL"]=""
S["RANLIB"]="ranlib"
S["AR"]="ar"
S["OBJDUMP"]="objdump"
S["LN_S"]="ln -s"
S["NM"]="nm"
S["ac_ct_DUMPBIN"]=""
S["DUMPBIN"]=""
S["LD"]="ld -m elf_x86_64"
S["FGREP"]="/usr/bin/grep -F"
S["EGREP"]="/usr/bin/grep -E"
S["GREP"]="/usr/bin/grep"
S["SED"]="/usr/bin/sed"
S["LIBTOOL"]="$(SHELL) $(top_builddir)/libtool"
S["am__fastdepCC_FALSE"]="#"
S["am__fastdepCC_TRUE"]=""
S["CCDEPMODE"]="depmode=gcc3"
S["AMDEPBACKSLASH"]="\\"
S["AMDEP_FALSE"]="#"
S["AMDEP_TRUE"]=""
S["am__quote"]=""
S["am__include"]="include"
S["DEPDIR"]=".deps"
S["OBJEXT"]="o"
S["EXEEXT"]=""
S["ac_ct_CC"]=""
S["CPPFLAGS"]=""
S["LDFLAGS"]=" "
S["CFLAGS"]="-g"
S["CC"]="gcc"
S["COMPPATH"]="."
S["MAINT"]="#"
S["MAINTAINER_MODE_FALSE"]=""
S["MAINTAINER_MODE_TRUE"]="#"
S["am__untar"]="${AMTAR} xf -"
S["am__tar"]="${AMTAR} chof - \"$$tardir\""
S["AMTAR"]="${SHELL} /home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/gcc-5.3.0/missing --run tar"
S["am__leading_dot"]="."
S["SET_MAKE"]=""
S["AWK"]="gawk"
S["mkdir_p"]="/usr/bin/mkdir -p"
S["MKDIR_P"]="/usr/bin/mkdir -p"
S["INSTALL_STRIP_PROGRAM"]="$(install_sh) -c -s"
S["STRIP"]="strip"
S["install_sh"]="${SHELL} /home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/gcc-5.3.0/install-sh"
S["MAKEINFO"]="/home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/gcc-5.3.0/missing makeinfo --split-size=5000000 --split-size=5000000"
S["AUTOHEADER"]="${SHELL} /home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/gcc-5.3.0/missing --run autoheader"
S["AUTOMAKE"]="${SHELL} /home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/gcc-5.3.0/missing --run automake-1.11"
S["AUTOCONF"]="${SHELL} /home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/gcc-5.3.0/missing --run autoconf"
S["ACLOCAL"]="${SHELL} /home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/gcc-5.3.0/missing --run aclocal-1.11"
S["VERSION"]="1.1.4"
S["PACKAGE"]="zlib"
S["CYGPATH_W"]="echo"
S["am__isrc"]=" -I$(srcdir)"
S["INSTALL_DATA"]="/usr/bin/install -c -m 644"
S["INSTALL_SCRIPT"]="/usr/bin/install -c"
S["INSTALL_PROGRAM"]="/usr/bin/install -c"
S["mkinstalldirs"]="/home/a59905/NUMA_Aware_Thesis/tools/KNL_Soft/gcc-5.3.0/mkinstalldirs"
S["target_os"]="linux-gnu"
S["target_vendor"]="unknown"
S["target_cpu"]="x86_64"
S["target"]="x86_64-unknown-linux-gnu"
S["host_os"]="linux-gnu"
S["host_vendor"]="unknown"
S["host_cpu"]="x86_64"
S["host"]="x86_64-unknown-linux-gnu"
S["build_os"]="linux-gnu"
S["build_vendor"]="unknown"
S["build_cpu"]="x86_64"
S["build"]="x86_64-unknown-linux-gnu"
S["multi_basedir"]="../../gcc-5.3.0/zlib/.."
S["target_alias"]="x86_64-unknown-linux-gnu"
S["host_alias"]="x86_64-unknown-linux-gnu"
S["build_alias"]="x86_64-unknown-linux-gnu"
S["LIBS"]=""
S["ECHO_T"]=""
S["ECHO_N"]="-n"
S["ECHO_C"]=""
S["DEFS"]="-DPACKAGE_NAME=\\\"\\\" -DPACKAGE_TARNAME=\\\"\\\" -DPACKAGE_VERSION=\\\"\\\" -DPACKAGE_STRING=\\\"\\\" -DPACKAGE_BUGREPORT=\\\"\\\" -DPACKAGE_URL=\\\"\\\" -DPACKAGE=\\\"zlib"\
"\\\" -DVERSION=\\\"1.1.4\\\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRING"\
"S_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\\\".libs/\\\" -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_GET"\
"PAGESIZE=1 -DHAVE_MMAP=1 -DHAVE_MEMCPY=1 -DHAVE_STRERROR=1 -DHAVE_UNISTD_H=1"
S["mandir"]="${datarootdir}/man"
S["localedir"]="${datarootdir}/locale"
S["libdir"]="${exec_prefix}/lib"
S["psdir"]="${docdir}"
S["pdfdir"]="${docdir}"
S["dvidir"]="${docdir}"
S["htmldir"]="${docdir}"
S["infodir"]="${datarootdir}/info"
S["docdir"]="${datarootdir}/doc/${PACKAGE}"
S["oldincludedir"]="/usr/include"
S["includedir"]="${prefix}/include"
S["localstatedir"]="${prefix}/var"
S["sharedstatedir"]="${prefix}/com"
S["sysconfdir"]="${prefix}/etc"
S["datadir"]="${datarootdir}"
S["datarootdir"]="${prefix}/share"
S["libexecdir"]="${exec_prefix}/libexec"
S["sbindir"]="${exec_prefix}/sbin"
S["bindir"]="${exec_prefix}/bin"
S["program_transform_name"]="s,y,y,"
S["prefix"]="/platform"
S["exec_prefix"]="${prefix}"
S["PACKAGE_URL"]=""
S["PACKAGE_BUGREPORT"]=""
S["PACKAGE_STRING"]=""
S["PACKAGE_VERSION"]=""
S["PACKAGE_TARNAME"]=""
S["PACKAGE_NAME"]=""
S["PATH_SEPARATOR"]=":"
S["SHELL"]="/bin/sh"
  for (key in S) S_is_set[key] = 1
  FS = ""

}
{
  line = $ 0
  nfields = split(line, field, "@")
  substed = 0
  len = length(field[1])
  for (i = 2; i < nfields; i++) {
    key = field[i]
    keylen = length(key)
    if (S_is_set[key]) {
      value = S[key]
      line = substr(line, 1, len) "" value "" substr(line, len + keylen + 3)
      len += length(value) + length(field[++i])
      substed = 1
    } else
      len += 1 + keylen
  }

  print line
}

